// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2SvB2nPfJ2DSxzK8Xy6G0nP7OCsKvDi8',
    appId: '1:900241182709:web:03e92bda60195eb45a9abc',
    messagingSenderId: '900241182709',
    projectId: 'myfirebaseproject06mei2024',
    authDomain: 'myfirebaseproject06mei2024.firebaseapp.com',
    storageBucket: 'myfirebaseproject06mei2024.appspot.com',
    measurementId: 'G-86YGPET2V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDADtBlmqgoxv7oK9Sjf1afeoTyPrh_Uzk',
    appId: '1:900241182709:android:8927585dfab6bb135a9abc',
    messagingSenderId: '900241182709',
    projectId: 'myfirebaseproject06mei2024',
    storageBucket: 'myfirebaseproject06mei2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYCFhBGkATG6ppIPEXgblj8SiA-1_OQUo',
    appId: '1:900241182709:ios:90955f55433e9f335a9abc',
    messagingSenderId: '900241182709',
    projectId: 'myfirebaseproject06mei2024',
    storageBucket: 'myfirebaseproject06mei2024.appspot.com',
    iosBundleId: 'com.example.apiFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYCFhBGkATG6ppIPEXgblj8SiA-1_OQUo',
    appId: '1:900241182709:ios:90955f55433e9f335a9abc',
    messagingSenderId: '900241182709',
    projectId: 'myfirebaseproject06mei2024',
    storageBucket: 'myfirebaseproject06mei2024.appspot.com',
    iosBundleId: 'com.example.apiFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2SvB2nPfJ2DSxzK8Xy6G0nP7OCsKvDi8',
    appId: '1:900241182709:web:eb4f1907ac1f45765a9abc',
    messagingSenderId: '900241182709',
    projectId: 'myfirebaseproject06mei2024',
    authDomain: 'myfirebaseproject06mei2024.firebaseapp.com',
    storageBucket: 'myfirebaseproject06mei2024.appspot.com',
    measurementId: 'G-41CCGFH1GG',
  );
}
